title: Recently Read & Watched
description: My Personal Reading & Watching
author: Rifat Yuce Dincer
github: https://github.com/yucedincer
about: I'm a business development exec turned data scientist who codes in Python & R and enjoys scaring the data. I geek out on gastronomy, motorcycles and snowboarding.
# disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /projects/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/rifatyucedincer"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/yucedincer"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Resume
      url: /resume/    
    # - text: XML Feed
    #   url: /feed.xml

url: "https://yucedincer.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
